# Generated by Django 2.2.6 on 2019-12-05 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(default='', max_length=60, validators=[django.core.validators.MaxLengthValidator(60, 'Error en la longitud'), django.core.validators.MinLengthValidator(5, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[a-z-A-Z ]+$', 'No se permiten caracteres especiales')])),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(default='', max_length=60, validators=[django.core.validators.MaxLengthValidator(60, 'Error en la longitud'), django.core.validators.MinLengthValidator(5, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[a-z-A-Z ]+$', 'No se permiten caracteres especiales')])),
                ('unidad_medida', models.CharField(choices=[('CON', 'Congresos'), ('EVN', 'Eventos'), ('CONF', 'Conferencias')], default='', max_length=4)),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100, 'El valor máximo permitido es 100'), django.core.validators.MinValueValidator(1, 'El valor mínimo permitido es 1')])),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(1, 'El valor mínimo permitido es 1'), django.core.validators.MaxValueValidator(100000000, 'El valor máximo permitido son 100000000')])),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Proyectos')),
            ],
        ),
    ]
