# Generated by Django 2.2.7 on 2019-12-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
