# Generated by Django 2.2.6 on 2019-12-05 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, validators=[django.core.validators.MaxLengthValidator(100, 'Error de longitud'), django.core.validators.MinLengthValidator(5, 'Error de longitud mínima'), django.core.validators.RegexValidator('^[a-zA-zÁÉÍÓÚñáéíóúÑ][a-zA-z ÁÉÍÓÚñáéíóúÑ]+$', 'Formato del nombre del programa es incorrecto, favor de verificarlo.')], verbose_name='Nombre del programa:')),
                ('anio_ejercicio_fiscal', models.IntegerField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]{4,4}$', 'El año fiscal debe de contener 4 dígitos.')], verbose_name='Año Fiscal:')),
                ('recurso_asignado', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0, 'El valor mínimo permitido es 0'), django.core.validators.MaxValueValidator(6000000, 'El valor máximo permitido son 6000000')], verbose_name='Recurso Asignado:')),
                ('fuente', models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-zÁÉÍÓÚñáéíóúÑ][a-zA-z ÁÉÍÓÚñáéíóúÑ]+$', 'Formato de la fuente del programa es incorrecto, favor de verificarlo.'), django.core.validators.MaxLengthValidator(100, 'Error de longitud'), django.core.validators.MinLengthValidator(5, 'Error de longitud mínima')], verbose_name='Fuente:')),
                ('tipo', models.CharField(choices=[('MEN', 'Mensual'), ('BIM', 'Bimestral'), ('TRI', 'Trimestral')], default='', max_length=3, verbose_name='Tipo de Apoyo:')),
                ('status', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='', max_length=3, verbose_name='Estatus Programa:')),
                ('tipo_programa_p', models.CharField(choices=[('APO', 'Apoyo'), ('SER', 'Servicio'), ('FOM', 'Fomento')], default='', max_length=3, verbose_name='Tipo de Programa Presupuestario:')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_partida', models.IntegerField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]{4,4}$', 'El número de partida debe de contener 4 dígitos.')])),
                ('nombre_partida', models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-zÁÉÍÓÚñáéíóúÑ][a-zA-z ÁÉÍÓÚñáéíóúÑ]+$', 'Formato del nombre de la partida es incorrecto, favor de verificarlo.'), django.core.validators.MaxLengthValidator(70, 'Error de longitud'), django.core.validators.MinLengthValidator(5, 'Error de longitud mínima')])),
                ('monto_partida', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0, 'El valor mínimo permitido es 0'), django.core.validators.MaxValueValidator(6000000, 'El valor máximo permitido son 6000000')])),
                ('programa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='programas.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='MetaReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_actividades_r', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El valor mínimo permitido es 0'), django.core.validators.MaxValueValidator(100, 'El valor máximo permitido son 6000000')], verbose_name='No. Actividades:')),
                ('numero_beneficiarios_r', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El valor mínimo permitido es 0'), django.core.validators.MaxValueValidator(9000000, 'El valor máximo permitido son 6000000')], verbose_name='Beneficiarios:')),
                ('numero_hombres_r', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El valor mínimo permitido es 0'), django.core.validators.MaxValueValidator(9000000, 'El valor máximo permitido son 6000000')], verbose_name='Hombres:')),
                ('numero_mujeres_r', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El valor mínimo permitido es 0'), django.core.validators.MaxValueValidator(9000000, 'El valor máximo permitido son 6000000')], verbose_name='Mujeres:')),
                ('edad_r', models.CharField(choices=[('NAD', 'Niños y Adolescentes (11-17 años)'), ('JOV', 'Jóvenes (18 a 29 años)'), ('ADU', 'Adultos (30+ años)')], default='', max_length=3, verbose_name='Rango:')),
                ('meta_esperada_r', models.BooleanField(default=True)),
                ('programa_r', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='metas_r', to='programas.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='MetaPrograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_actividades', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El valor mínimo permitido es 0'), django.core.validators.MaxValueValidator(100, 'El valor máximo permitido son 6000000')], verbose_name='No. Actividades:')),
                ('numero_beneficiarios', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El valor mínimo permitido es 0'), django.core.validators.MaxValueValidator(9000000, 'El valor máximo permitido son 6000000')], verbose_name='Beneficiarios:')),
                ('numero_hombres', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El valor mínimo permitido es 0'), django.core.validators.MaxValueValidator(9000000, 'El valor máximo permitido son 6000000')], verbose_name='Hombres:')),
                ('numero_mujeres', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El valor mínimo permitido es 0'), django.core.validators.MaxValueValidator(9000000, 'El valor máximo permitido son 6000000')], verbose_name='Mujeres:')),
                ('edad', models.CharField(choices=[('NAD', 'Niños y Adolescentes (11-17 años)'), ('JOV', 'Jóvenes (18 a 29 años)'), ('ADU', 'Adultos (30+ años)')], default='', max_length=3, verbose_name='Rango:')),
                ('meta_esperada', models.BooleanField(default=True)),
                ('programa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='programas.Programa')),
            ],
        ),
    ]
