# Generated by Django 2.2.6 on 2019-12-05 16:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subprograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'blank': 'El nombre no puede estar vacío.', 'required': 'El nombre no puede estar vacío.'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'El nombre debe ser de por lo menos 5 caracteres.'), django.core.validators.MaxLengthValidator(50, 'El nombre no puede pasar los 50 caracteres.'), django.core.validators.RegexValidator(code='nombre_invalido', message='Solo se permiten letras.', regex='^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$')], verbose_name='Nombre del Subprograma:')),
                ('presupuesto', models.DecimalField(decimal_places=3, error_messages={'blank': 'El presupuesto no puede estar vacío.', 'invalid': 'El presupuesto debe ser numérico.'}, max_digits=15, validators=[django.core.validators.MinValueValidator(0, 'No puede tener valores negativos')], verbose_name='Presupuesto:')),
                ('estatus', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo')], default='ACT', max_length=3, verbose_name='Estatus Subprograma:')),
                ('programa', models.ForeignKey(error_messages={'blank': 'Debes indicar un programa.', 'required': 'Debes indicar un programa.'}, on_delete=django.db.models.deletion.CASCADE, to='programas.Programa', verbose_name='Seleccionar programa: ')),
                ('responsable', models.ForeignKey(error_messages={'blank': 'Debes indicar un responsable.', 'required': 'Debes indicar un responsable.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable:')),
            ],
        ),
    ]
