# Generated by Django 2.2.6 on 2019-12-03 17:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'], 'Formato de imagen inválido.')], verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'La longitud mínima del nombre es de 2 caracteres.'), django.core.validators.MaxLengthValidator(50, 'La longitud máxima del nombre es de 50 caracteres.'), django.core.validators.RegexValidator('^[A-Za-zÁÉÍÓÚñáéíóúÑ]+((\\s)?(([A-Za-zÁÉÍÓÚñáéíóúÑ])+))*$', 'Formato de nombre incorrecto, favor de veriicarlo.')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='primer_apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'La longitud mínima del primer apellido es de 2 caracteres.'), django.core.validators.MaxLengthValidator(50, 'La longitud máxima del primer apellido es de 50 caracteres.'), django.core.validators.RegexValidator('^[A-Za-zÁÉÍÓÚñáéíóúÑ]+((\\s)?(([A-Za-zÁÉÍÓÚñáéíóúÑ])+))*$', 'Formato del primer apellido incorrecto, favor de veriicarlo.')], verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'La longitud mínima del segundo apellido es de 2 caracteres.'), django.core.validators.MaxLengthValidator(50, 'La longitud máxima del segundo apellido es de 50 caracteres.'), django.core.validators.RegexValidator('^[A-Za-zÁÉÍÓÚñáéíóúÑ]+((\\s)?(([A-Za-zÁÉÍÓÚñáéíóúÑ])+))*$', 'Formato del segundo apellido incorrecto, favor de veriicarlo.')], verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10,10}$'), django.core.validators.MinLengthValidator(10, 'El número telefónico debe contener 10 dígitos.'), django.core.validators.MaxLengthValidator(10, 'El número telefónico debe contener 10 dígitos.')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='usuario',
            field=models.OneToOneField(error_messages={'required': 'El usuario es requerida, favor de indicar sus datos.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
