# Generated by Django 2.2.6 on 2019-12-05 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20191203_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativo',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'La longitud mínima del nombre es de 2 caracteres.'), django.core.validators.MaxLengthValidator(50, 'La longitud máxima del nombre es de 50 caracteres.'), django.core.validators.RegexValidator('^[A-Za-zÁÉÍÓÚñáéíóúÑ]+((\\s)?[A-Za-zÁÉÍÓÚñáéíóúÑ]+)*$', 'Formato de nombre incorrecto, favor de veriicarlo.')], verbose_name='Nombre'),
        ),
    ]
