# Generated by Django 2.2.6 on 2019-12-07 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('modulos', models.CharField(choices=[('RPG', 'Progrmas'), ('SBPRG', 'Subprogramas'), ('PRY', 'Proyectos')], error_messages={'blank': 'Debes escoger el tipo de reporte.', 'required': 'Debes escoger el tipo de reporte.'}, max_length=15, validators=[django.core.validators.MinLengthValidator(
                    5, 'El nombre debe ser de por lo menos 5 caracteres.'), django.core.validators.MaxLengthValidator(15, 'El nombre no puede pasar los 15 caracteres.'), django.core.validators.RegexValidator(code='nombre_invalido', message='Solo se permiten letras.', regex='^[A-Za-zÀ-ÿ\\u00E0-\\u00FC ]+$')], verbose_name='Escoge el tipo de reporte:')),
            ],
        ),
    ]
