# Generated by Django 2.2.6 on 2019-12-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reportes',
        ),
    ]
