# Generated by Django 2.2.7 on 2020-03-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='componentes.Componentes', verbose_name='Componentes'),
        ),
    ]
